# 工作流名称
name: Build and Deploy 
# 触发工作流的事件
on: [push]
# 工作流里的任务
jobs:
  # 任务名，构建并部署到GitHubPages
  build-and-deploy:
    # 运行所需要的虚拟机环境
    runs-on: ubuntu-latest
    # 任务里的运行步骤
    steps:
    # 步骤名
    - name: Checkout
      # 使用actions/checkout@master操作（引用其他的actions）
      uses: actions/checkout@master
    # 步骤名
    - name: vuepress-deploy
      # 引用其他的actions。用于构建并部署到GitHubPages
      uses: jenkey2011/vuepress-deploy@master
      # 所需的环境变量
      env:
        # github的token
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # 你要操作的目标仓库
        TARGET_REPO: liawnliu/blog-vuepress
        # 构建结果存储的分支
        TARGET_BRANCH: gh_pages
        # 要使用的构建命令
        BUILD_SCRIPT: yarn && yarn new-build
        # 构建结果存储目录
        BUILD_DIR: docs/.vuepress/dist/